### ISSUE TITLE
PT.M: dark mode missing styling

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#101]
### login
- [ ] password / email hints are light theme (meaning dark text)
### home tab
- [x] info page
- [x] goal information (below activity information)
### profile-tab
- [x] goal dialog circle too dark to be visible in dark mode
- [x] goal dialog description text
- [x] chair info dialog is light theme
- [x] birthday dialog is light theme
- [x] gender dialog is light theme
- [x] chair make dialog is light theme

**Comment by p-ranav** [comment]
![Screenshot from 2019-08-20 10-32-08](https://user-images.githubusercontent.com/8450091/63361531-edb11800-c335-11e9-8e9b-5e7fa908320b.png)
