### ISSUE TITLE
Profile Page Behaviorial Issues

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#107]
- [ ] - Birthday does not persist in Kinvey
- [x] - Weight and Height do not correctly initialize
- [x] - Weight and Height do not persist in Kinvey
- [x] - Coast Time does not persist in Kinvey
- [x] - Distance does not persist in Kinvey

**Comment by p-ranav** [comment]
Persisted Coast Time and Distance Activity Goals: https://github.com/Max-Mobility/permobil-client/commit/e7b0f256598e72580fa69256d5b5808a8ae32fb8
