### ISSUE TITLE
Create new App for PushTracker ecosystem in Kinvey

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#112]
### Configuration:
- [x] ios push notifications
- [x] android push notifications
- [x] addition to private keys repo
### Files:
- [x] translation files
- [x] OTA firmware files
### Required Collections:
- [x] SmartDriveUsage
- [x] SmartDriveSettings
- [x] SmartDriveErrors
- [x] SmartDrives
- [x] PushTrackerActivity

**Comment by finger563** [comment]
I've added you two to the development environment for the pushtracker app so we can work through designing the collections / storage / user info as we configure it

**Comment by bradmartin** [comment]
I think we have Kinvey configured well enough for now since we're starting testing. Can open new issue with specifics if we missed anything or need changes 👍
