### ISSUE TITLE
Modal Dialog Behavioral issues

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#113]
- [x] Profile-settings dialog doesn't animate in / out - it simply flashes into and out of existence. It should animate in just like the Coast Time / Distance goal dialogs
- [x] Profile-tab modal dialogs for coast time / distance / profile-settings don't cover the tab navigation, meaning users can switch away from the tab they're currently on while the modal is up. Then when they switch back the modal dialog will be up. Probably want to have the modal dialog cover the tabs to prevent such navigation. This will help it have similar look / feel as the info modal dialog on the home-tab.
- [x] home-tab info modal dialog should animate into position similarly to the others.

**Comment by bradmartin** [comment]
@finger563 - `

- home-tab info modal` - I'd make this a route like profile-settings and drop the modal dialog approach to it. There is a bug with full screen modals animating on Android in NS right now so no way around it ATM. Using a route like `profile-settings.component` would give us what we want though.

- The dialogs not covering the tabview are because they're inside the `page` as layouts. I didn't like this approach TBH. Moving it outside, you could possibly create a second `root frame` and then we put those dialogs in there and then it'll cover the tabview because it would be outside of the main `tabview root frame`.

Or scrap all that and we basically go with a different UI for all of the dialogs for settings/config options. Nothing was really consistent in terms of look/feel for all the various options we needed when I looked for plugins.

We could move to the `material-bottomsheet` but it was a bit more work isolating the components to inject into it because it's the same API as the modal dialog so I went for quicker right now.

**Comment by finger563** [comment]
yea I like the `profile-settings.component` changes - and I think moving to a second root frame might be the way to go

**Comment by finger563** [comment]
after the update in d15a4fe it seems like the first transition into `profile-settings` does not use the transition, and instead pops in.

**Comment by bradmartin** [comment]
Closing in favor of https://github.com/Max-Mobility/permobil-client/pull/158/files which fixe android modal animations. So now we can present all of these as actual modals and have them animate in full screen mode on both platforms.
