### ISSUE TITLE
Home-tab Improvements

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#126]
- [x] Goal display (e.g. `Travel X miles per day) is not data-bound in any way
- [x] Goal display (above) is not styled to support dark theme and is not visible when dark theme is enabled.
- [x] no graphs shown for historical goal data
- [x] no goal data shown for coast time goal

**Comment by p-ranav** [comment]
- [ ] ActivityIndicator loading wheel when loading weekly activity
- [ ] Fix chart label color in dark mode
- [ ] Look into using worker threads for loading weekly activity
- [ ] Load chart activity just once - Sufficient for weekly activity

**Comment by p-ranav** [comment]
- [ ] Overhaul econdary dashboard with detailed information
- [ ] Fix spacing b/w primary and secondary dashboard to look more like Google Fit
