### ISSUE TITLE
Update profile settings in PT.W

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#128]
To match PT.M:
- [x] chair info -> chair make
- [x] add chair type
- [ ] units selection should be similar (or only done on phone?)

**Comment by finger563** [comment]
closing for now - we'll allow the units configuration on the watch, but keep it simple so that it's just a single selector (as opposed to the way it is in mobile).
