### ISSUE TITLE
Draft implementation of Activity Tab

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#149]
Design based on Google Fit

### Day View:
- [x] Activity Plotting for 24 hours in the day
- [x] Next Day and Previous Day control
- [ ] Trackball control and viz on the RadCartesianChart
- [x] Connect to PushTrackerActivity collection for current user and fetch data instead of mocking
- [ ] Disable next day button if current day is today

### Week View
- [x] Show all days of that week and plot summary activity
- [x] Next Week and Previous Week control
- [x] Select day in week and switch to day view for selected day
- [ ] Trackball control and viz on the RadCartesianChart
- [x] Connect to PushTrackerActivity collection for current user and fetch data instead of mocking

### Month View
- [x] Show all days in month with RadCalendar
- [x] Next month and previous month control
- [x] Select day in month and switch to day view for selected day
- [ ] Figure out how to show bubbles of activity per day in month view
- [x] Disable pinch to year view, tap, swipe and scroll controls
- [x] Connect to PushTrackerActivity collection for current user and fetch data instead of mocking

### Misc.
- [x] ActivityService to pull data from PushTrackerActivity collection
- [x] Day in view should be consistent across Day, Week and Month views

**Comment by finger563** [comment]
related #24

**Comment by p-ranav** [comment]
## Daily Activity Tab

![Screenshot_20190815_112214_com permobil pushtracker](https://user-images.githubusercontent.com/8450091/63109525-1066b980-bf4f-11e9-9a14-1d315dc4bf90.jpg)

**Comment by p-ranav** [comment]
## Daily Activity

![screenshot_20190815-134838](https://user-images.githubusercontent.com/8450091/63118627-dce25a00-bf63-11e9-816c-12d3ffee05b3.png)

**Comment by p-ranav** [comment]
## Weekly Activity
![Screenshot_20190816_124334_com permobil pushtracker](https://user-images.githubusercontent.com/8450091/63187021-7d4b8380-c023-11e9-91a6-9aab33f36646.jpg)

**Comment by p-ranav** [comment]
## Weekly Activity

![Screenshot_20190816_124331_com permobil pushtracker](https://user-images.githubusercontent.com/8450091/63187040-89374580-c023-11e9-937e-baf859d59aad.jpg)

**Comment by p-ranav** [comment]
## Monthly Activity

![Screenshot_20190816_124334_com permobil pushtracker](https://user-images.githubusercontent.com/8450091/63187057-918f8080-c023-11e9-95fa-0416ad0a376f.jpg)
