### ISSUE TITLE
Pull distance either from server or smartdrive mx2+ app for showing to user

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#164]
- [x] Service Pulling from Server (enhancements)
- [x] App pulling from server (plots)
- [ ] service pulling from mx2+ app
- [ ] app pulling from mx2+ app

**Comment by finger563** [comment]
look into using a content provider ([see example code here](https://github.com/lalit3686/CustomContentProviderDemo)) or potentially directly sharing the db [as discussed here](https://stackoverflow.com/questions/7053809/share-sqlite-database-between-2-android-apps)

**Comment by finger563** [comment]
Based on [this stackoverflow](https://stackoverflow.com/questions/6030321/android-retrieving-shared-preferences-of-other-application) we can just use the shared preferences and set them up to be `world_readable` - which will enable other apps to read these preferences like we want.
