### ISSUE TITLE
Update styling of switches in profile-settings page

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#177]
- [x] they should dock on the right side of the screen similarly to how the equivalent switch controls dock in the fit's settings 
- [x] the circle / button for it should be grey when not activated
- [ ] some explanatory text for the setting underneath the title

**Comment by bradmartin** [comment]
not sure if we have the `description` for the settings, if so I'll dump em in translation and finish the unchecked default styling on load and close this one.
