### ISSUE TITLE
Journey-Tab UI Layout

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#23]
![journey](https://user-images.githubusercontent.com/6006148/60134123-6fd0f600-9764-11e9-8b29-726863b7ede8.png)

**Comment by finger563** [comment]
I think we've got the data to show this tab now - we're getting the drive / coast distances, pushes, and coast time from the databases with half-hourly increments, so we should be able to determine periods of activity which are contiguous and link them together (e.g. 9:00 - 11:30 morning roll), where there are two possible activities:

1. roll - default; used when there is no drive / distance data, or when the coast data is significantly more than drive
2. drive - used when there is distance data and drive is a significant portion of coast (e.g. > 30%)

We can split up contiguous segments of data into multiple activities by looking at how much driving occurred during the segments

**Comment by p-ranav** [comment]
We can't show the map for each journey. Can Ken update the layout?

**Comment by bradmartin** [comment]
Just heads up you'll want to use a listview and templates inside the listview for this. Not sure what I initially did on the placeholder for it.

**Comment by p-ranav** [comment]
> Just heads up you'll want to use a listview and templates inside the listview for this. Not sure what I initially did on the placeholder for it.

Yeah this is how the placeholder's setup. 

```xml
<ListView row="1" colSpan="4" height="100%" [items]="journeyItems" (itemTap)="onJourneyItemTap($event)" class="list-group">
  <ng-template let-item="item" let-odd="odd" let-even="even">
    <GridLayout rows="*, *" columns="*, *">
      <Label [text]="item.description" class="list-group-item"></Label>
    </GridLayout>
  </ng-template>
</ListView>
```

**Comment by p-ranav** [comment]
- [x] Journey tab shows bursts of activity
- [x] Group daily activity records into intervals of activity, further grouped by time of day, e.g., 10 - 11 AM Morning roll, following by 2:30 - 3:30 PM afternoon drive etc.
- [x] Show coast time, push count and coast distance for each interval
- [x] Show start time and end time of interval
- [x] Order journeys by most recent - Most recent activity at the top
- [ ] Show older journeys as the user scrolls down - Implement infinite scrolling

**Comment by p-ranav** [comment]
![Journey Tab - Dark Mode](https://user-images.githubusercontent.com/8450091/64358410-0a06b300-cfcc-11e9-893c-934d5ef62b81.jpg)

Closing this issue for now since a major part of the layout and logic is done. 

Minor improvements: 
- [ ] If there are no journeys yet, don't show an empty page - Show some text or something
- [ ] Update icons for DEFAULT view
- [ ] Hide activity that isn't really activity, e.g., coast distance of 0.02 miles is not worth an entry
