### ISSUE TITLE
Handle logout / token invalidation

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#256]
- [ ] detect logout (401?) failures when sending data
- [ ] invalidate login credentials to prevent further attempts
- [ ] Inform the user that the app has been logged out and needs to be re-connected with the mobile app
