### ISSUE TITLE
Open PushTracker mobile app on phone if it is installed

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#265]
### Android
- [x] update service library to expose capabilities that are discoverable via the wear os node / capability api  - enables wearos determining if the app is installed or not
- [x] update service library (https://github.com/max-mobility/wearosmessaging) to have a path which allows starting intents in android

### iOS
- [x] register iOS mobile app with url [see this link](https://stackoverflow.com/questions/25883113/open-ios-app-from-browser) and [these docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html)
    We should use [this {N} library](https://github.com/hypery2k/nativescript-urlhandler) to support url handling / opening on ios :)

### WearOS
- [x] expose capabilities that are discoverable via the wear os node / capability api - enables android app determining if the app(s) are installed or not
- [ ] update service to have a path which allows starting intents for both PushTracker WearOS and SmartDrive MX2+ WearOS
- [x] show `Open on Phone` confirmation activity [see these docs](https://developer.android.com/training/wearables/ui/confirm)

**Comment by finger563** [comment]
Related to https://github.com/Max-Mobility/WearOsMessaging/issues/1

**Comment by finger563** [comment]
@gcastro103 is the library mentioned above the solution to opening the app on the phones? or what did you come up with?

**Comment by finger563** [comment]
closing for now - we don't need more services to open PT.W and SD.W - to open both we'd need to use URI handling as we do in the mobile app, and there's not (currently) a huge benefit to doing so

currently the wear apps cannot completely tell if the mobile app is installed on an iphone - but that's separate from this issue.
