### ISSUE TITLE
Update PT Serial Number field on profile-tab based on the configuration

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#279]
- [x] If the user has `Switch Control` then we only show SD serial number, no PT or E2 serial number
- [x] if the user has `PushTracker` then we show the current `PushTracker` serial number field that includes the QR code reader for reading the OGPT qr code
- [x] if the user has `PushTracker E2` then we show a read-only `PushTracker E2` serial number field which shows the serial number saved with the user account (comes from the wear apps). If the user presses on the field, then we show a dialog indicating that the serial number comes from the wear os apps.
