### ISSUE TITLE
PushTracker WearOS UI

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#28]
From permobil-wear created by [bradmartin](https://github.com/bradmartin): Max-Mobility/permobil-wear#75  

[PushTracker Wear OS Flow.pdf](https://github.com/Max-Mobility/permobil-wear/files/3218527/PushTracker.Wear.OS.Flow.pdf)

<img width="1044" alt="flow2" src="https://user-images.githubusercontent.com/6006148/58355976-9f29d580-7e3b-11e9-9083-d868b264e91f.png">

_Originally posted by @bradmartin in https://github.com/Max-Mobility/permobil-wear/issues/70#issuecomment-495783952_

- [x] Main Activity Display (move minutes / heart points / # pushes)
- [ ] Specific Activity Display (distance, high stress actions)
- [x] Distance Graph for Goal comparison
- [x] Profile
  - [x] Edit profile
    - [x] Weight
    - [x] Height
    - [x] Chair Info
  - [x] Edit Distance Goal
  - [x] Edit Units Selection

**Comment by finger563** [comment]
Closing since the majority of the UI is complete - the specific activity display will come post-launch when that model has been further developed
