### ISSUE TITLE
Develop service / module for watch communications

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#282]
Related to #54 & #253 & #265 - we have some working communications (on android) for talking to the wear os apps - this will need to be cross platform so we need to build a service / module which can manage the platform specific code (and may require the use of the bluetooth service on ios) so that the mobile app can query the state and send / receive data to / from the wear os apps 

Responsibilities:
- [x] provide a way to search for the wear os apps and determine if they are installed and operational.  
    - [x] Android:
      * This will use the Node / Capability api so that the mobile app can query if any nodes connected have the requested app capability. note: this will only be able to look for the pushtracker wear os app (this is fine).
    - [x] iOS:
      * This will use the bluetooth service to scan for a specific service (TBD) which is advertised by the pusthracker wear app
- [x] allow the mobile app to send the authorization data to the PT.W app and determine if it succeeded
    - [x] Android:
      * use the data layer api (as is done right now)
    - [x] iOS: 
      * scan for the service, connect to the device, send the data, disconnect
- [ ] Expose service allowing the wear app to start / open the mobile app
    - [ ] Android:
      * Use and configure the service provided by wearosmessaging library
    - [x] iOS:
      * register for appropriate uri/url handling so that when the wearos app sends an intent with a specific uri, it will open using / inside the app

**Comment by bradmartin** [comment]
Just a note before wiring it up. It should not be an angular 'service' so to speak. Because then it won't work in the wear apps. Just want to make sure we don't start off on the wrong path.

Having a dependency on our bluetooth plugin is 👌 but just no hard deps on angular.

So initial thinking, this can just be a `module` we put in `@permobil/nativescript` since we'll want to run it on multiple NS apps. So then nothing app specific should be in it and any UI/UX needs to be handled in the specific apps accordingly.

I'll go ahead and stub the module in the `@permobil` directory with something for the working use case we have as of now.

**Comment by bradmartin** [comment]
Actually come to think of it, a 'plugin' might be better here because we have native dependencies on the android library right now so it would avoid having to duplicate some things in the apps specifically.

So I'll stub that out instead.

**Comment by finger563** [comment]
closing for now - we don't need the service to start the app since we're using the URI method.

**Comment by gearshead** [comment]
Some really interesting work here.(*_*)
