### ISSUE TITLE
Update the palette for the PushTracker mobile app

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#306]
There are currently too many colors in pt.m. Update the colors to be more consistent, per Ben's feedback.

- [x] Use fewer colors in both default and dark mode - We don't need every shade of blue
- [x] Use Material design suggestions when skinning dark mode per https://material.io/design/color/dark-theme.html
- [x] Use a better linear gradient for main goal circle in home tab
