### ISSUE TITLE
Home tab ios style issues

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#328]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/213467/65460767-40d82800-de18-11e9-9c17-50aec68e5fde.png)

- [x] outer circle is ellipse instead of circle
- [x] inner circle has no margin to the filled circle
~- [ ] top notification area / status bar area has white background on home tab (but not on journey or profile tab)~ have moved this to #334 
- [x] chart labels offset
- [x] charts not centered on the screen

**Comment by finger563** [comment]
![Chart label issue](https://i.imgur.com/g2IYvQF.jpg)
