### ISSUE TITLE
Break apart collections to maintain typing

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#330]
Right now the collections on kinvey contain multiple types of data and a `data_type` field to allow us to select the right data - but this increases overhead and opportunities for errors, we should simply have strongly typed collections with specific names for their types.
- [x] update collection names (pushtracker / smartdrive daily activity)
- [x] add new collections for types that are currently colocated in other collections (pushtracker / smartdrive weekly activity)
- [x] update collection hooks for pushtracker / smartdrive daily activity
- [x] update pushtracker mobile app to pull / write from / to correct databases
- [x] update pushtracker wear to write to correct database and not add `data_type`
- [x] update smartdrive wear to write to correct database and not add `data_type`

**Comment by p-ranav** [comment]
What do you think of `DailyPushTrackerActivity`, `DailySmartDriveUsage`, `WeeklyPushTrackerActivity`, and `WeeklySmartDriveUsage` as the new collection names?

We can prefix qualifiers like `Daily` or `Weekly` or `Monthly` just like any other qualifier, e.g., `const int`

**Comment by finger563** [comment]
Sounds good to me

**Comment by p-ranav** [comment]
Close once all updates are verified to be OK.

**Comment by finger563** [comment]
Have tested:
- [ ] smartdrive daily usage going to right place
- [ ] smartdrive weekly usage being created
- [ ] smartdrive weekly usage being pulled / displayed properly
- [ ] pushtracker daily usage going to right place from pt.w
- [ ] pushtracker daily usage going to right place from pt.m
- [ ] pushtracker weekly usage being created
- [ ] pushtracker weekly usage being pulled displayed correctly
