### ISSUE TITLE
ios theme issues

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#334]
##### general
- [ ] in dark mode, the tabs which have dark notification / status area make the icons (which are black) in that area unreadable.sheet
##### home page
- [x] chart styles don't update when changing themes (from dark to light) - the charts retain a black background, but the text also goes black
- [x] in dark mode, the home tab has a white notification / status area (#328 )
- [x] chart y axis labels are cut off a little on the right (if they have more than one character, e.g. decimals)
##### profile tab
- [x] bottom sheet dialogs don't have proper styles in dark mode so the text is unreadable
- [x] highlighted setting on profile-tab stays highlighted after clicking away from the bottom 
##### profile settings tab
- [x] bottom sheet dialogs don't have proper styles in dark mode so the text is unreadable
- [ ] changing theme takes ~5-10 seconds
##### journey tab
- [x] elements are unreadable in dark mode (#332 )
##### activity component
- [x] selected plot (coast / push / distance) buttons are tiny and hard to press

**Comment by bradmartin** [comment]
bottom-sheet fix is in local fork for now - issue on plugin repo https://github.com/Akylas/nativescript-material-components/issues/64 

basically the plugin code to check the backgroundcolor is exec'd too early for the template to provide the value when it's `[]` bound. Wrapped in a timeout on our local fork to fix this for now.

**Comment by bradmartin** [comment]
Closing this issue for now and opening new issues for the two remaining items for easier tracking.
