### ISSUE TITLE
Update template of bottomsheet

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#341]
- [x] add optional prefixes for text fields
- [x] add control over default keyboard type (default standard)
- [x] variable number of text fields (`*ngFor`-ed for even spacing)
