### ISSUE TITLE
wireless updates issues on ios

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#353]
- [x] circles are not circles - they don't have width / height set explicitly (see #328 )
- [x] no pushtracker dialog is not translated
- [x] crash when searching for firmwares
- [x] crash when pressing retry on pushtracker ota
- [x] alert dialogs don't show on ios : *move to either toast (no action) or snackbar (with action)*

**Comment by finger563** [comment]
related to [this issue](https://github.com/NativeScript/NativeScript/issues/1809)

**Comment by finger563** [comment]
will instead move from dialogs to snackbars which can have actions
