### ISSUE TITLE
Design & Implement Device Setup Page 

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#392]
Design a page that shows right after the Configuration page during signup to setup comms with control device, e.g., PushTracker, PushTracker E2. 

##### iOS
- [x] show information (text / images) explaining the watch connect button and what it does, where it will be
- [x] scan for and display devices (address & name) that are nearby and advertising the wear-os-comms service
  - [x] if there are no devices - inform the user and let them know that the WearOs device must be on, with bluetooth on, and the PushTracker Wear App must be installed and open. Provide a button to re-scan
- [x] when the user selects a device, perform pairing, and save the pairing info to local storage. Then inform them that it succeeded and add a `Finish` button to the page for closing the dialog.
  - [x] if the information fails to send show a failure animation / text and a `retry` button
- [x] the page should also have a `Skip` button which informs the user that they can access this page from the profile-tab at any time and then closes the page.

##### Android
- [x] show information (text / images) explaining the watch connect button and what it does, where it will be
- [x] use wear-os-comms library (after #253 is finished) to see if there any nodes exposing the right capabilities (meaning that there is a paired WearOS device which has our app). 
  - [x] If there is not - inform the user that their wearOS watch must be on, bluetooth must be on, and the PushTracker Wear app should be running. Provide a button to re-scan.
- [x] When there is a device, inform the user that it succeeded and add a `Finish` button to the page for closing the dialog.
  - [x] if the information fails to send show a failure animation / text and a `retry` button
- [x] the page should also have a `Skip` button which informs the user that they can access this page from the profile-tab at any time and then closes the page.

#### PushTracker
- [x] explain the pairing process of the PT (re-use some text from SmartEval app)
- [x] explain the indications / icons of the pt icon in the app (text / images)
- [x] show `Finish` if the user has paired / connected a PT
- [x] the page should also have a `Skip` button which informs the user that they can access this page from the profile-tab at any time and then closes the page.

**Comment by finger563** [comment]
fully implemented on android and ios :)
