### ISSUE TITLE
PT.M / PT.W alpha app release

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#418]
- [x] #63 for android since they both share the same app ID - and this would (in theory) make installing it on the wear os device simpler
- [x] #368 ios Splash Screen
- [x] #381 PT.W splash screen
- [x] #392 Device setup page
- [x] #415 support page dark theme on ios
- [x] #422 pt.w android phone bug fix
- [x] #423 journey tab style fix
- [x] ensure version numbers of PT.M and PT.W match guidelines for packaged apps.

**Comment by bradmartin** [comment]
what's to do with `ensure version numbers of PT.M and PT.W match guidelines for packaged apps`?

**Comment by finger563** [comment]
i think so? i'm actually not really sure - it's something I vaguely remember reading when i was looking into #63

**Comment by finger563** [comment]
version code info copied from link in #63 : **https://developer.android.com/google/play/publishing/multiple-apks.html#VersionCodes**

**Comment by finger563** [comment]
looks like the version code thing is potentially only relevant if we're not using AABs

**Comment by bradmartin** [comment]
iOS 10004 is processing, will be on testflight shortly

**Comment by finger563** [comment]
Currently waiting on google for android / wear os release

**Comment by finger563** [comment]
now that google has allowed us to upload a new key we should be able to get an android release of PT.M and PT.W into the store - which is good timing now that PT.W has been heavily re-written :)

**Comment by finger563** [comment]
alphas are in the store for PT.M & PT.W on android and they do work together, so I think we can finally close this issue :)
