### ISSUE TITLE
Wireless Updates Component

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#42]
Will be a part of the settings page ( #25 ) which will only be visible if the user does not have / use a PushTracker E2 - meaning they have an older PushTracker or they only have a SmartDrive. Will use the OTA code that has been leveraged in both the Smart Evaluation app and the SmartDrive MX2+ app.

- [x] while in this page the user cannot press back / navigate back (same way as in Smart Evaluation)
- [x] the *info* button in the upper right shows the changes in this version / change history text for previous versions
- [x] only show PushTracker if the user has paired an original pushtracker device to the app (not an E2)
- [x] only show the smartdrive if the user has *not* paired an E2 to the app

**Comment by finger563** [comment]
@ken-max can we mock up a screen for wireless updates for the pushtracker mobile app?

**Comment by finger563** [comment]
Initial mock-up:
![PT-MOBILE-UPDATES](https://user-images.githubusercontent.com/213467/61217004-5f14ff80-a6d4-11e9-885f-cdead16adeee.png)

**Comment by p-ranav** [comment]
- [ ] OTA for SmartDrive
* - [ ] Scan for SmartDrives
* - [ ] If no SD detected, show alert dialog and allow to 'rescan'
* - [ ] If too many SDs detected (more than 1), show alert dialog and allow to 'rescan'
* - [ ] If exactly one SD detected, allow to 'Start' and go through the OTA process
* - [ ] Once OTA is done, show a green animated circle indicating that OTA is 100% done.  
- [ ] OTA for PushTracker

**Comment by p-ranav** [comment]
- [ ] Info buttons to show changelog
- [ ] Hide back navigation while OTA in progress

**Comment by bradmartin** [comment]
@p-ranav - can steal a bunch of the logic/code here https://github.com/PushTracker/EvalApp/blob/master/apps/smart-eval-app/app/modules/ota/ota.component.ts#L412 

depending on how we navigate to the wireless-updates component we'll need to disable the swipe back navigation. This shouldn't be the case with modals since we're not routing with the typical viewcontroller on iOS.

However, there should be some other good bits, especially handling the android hardware back button to prevent a user leaving. 

We added a confirmation in SEA (smart-eval app) to give the user the choice to cancel the updates and then navigate back. I guess we'll prob need the same in case some user accidentally starts the updates.

**Comment by p-ranav** [comment]
Makes sense. Yeah I'll need to (1) hide the back navigation in the mock action bar, and (2) hide the Android back navigation - I'll use what you've linked from the smart-eval app and show the user a confirmation dialog and then (hopefully) correctly tear down the OTA before going back.

**Comment by bradmartin** [comment]
I wouldn't bother hiding the actual navigation bar on the android device (hardware buttons) but just override the hardware back, which you can see in the link ^.  Might be what you meant 👍
