### ISSUE TITLE
journey tab updates

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#423]
- [x] fix style of today info
- [x] move refresh button from mock action bar (remove mock action bar) to where the activity indicator is (to reclaim vertical space) and show it when activity indicator is not shown
- [x] update `no more data` (#420 ) styling - to be in list view and at end of the list

see image below for style fixing:
![Screen Shot 2019-10-08 at 11 14 33 AM](https://user-images.githubusercontent.com/213467/66413479-114f2100-e9bd-11e9-8bea-7931ce12b829.png)

**Comment by finger563** [comment]
for reference the no more data *AND* today style issues shown above only happen *after* `no more data` is shown

**Comment by finger563** [comment]
Before:
![Screen Shot 2019-10-08 at 12 13 35 PM](https://user-images.githubusercontent.com/213467/66417198-1912c380-e9c5-11e9-91ef-e145ff37db23.png)
After:
![Screen Shot 2019-10-08 at 12 13 45 PM](https://user-images.githubusercontent.com/213467/66417207-1dd77780-e9c5-11e9-8d48-979d1ec3b5b4.png)
