### ISSUE TITLE
investigate `forgot password` issues

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#425]
doesn't seem to ever send an email to reset the password...

- [x] add email column to kinvey
- [x] update existing users in kinvey db to have proper email property
- [x] ensure all new users have email property set (via the app)

**Comment by finger563** [comment]
according to [this support ticket](https://support.kinvey.com/support/discussions/topics/12000004522) we need an `email` field on each user for the password reset and such to work

**Comment by finger563** [comment]
oddly adding the `email` property didn't seem to fix the issue :/

**Comment by p-ranav** [comment]
> oddly adding the `email` property didn't seem to fix the issue :/

Works for me now.
