### ISSUE TITLE
ios: dark theme bugs

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#427]
when app is on ios and in dark theme:
- [x] ~activity tab daily charts have light theme~ release build issue
- [x] ~home tab charts have light theme~ release build issue
- [x] activity tab month view is hard to read (looks like some dark theme some light?)
- [x] device-setup title not colored white so it's not visible

**Comment by finger563** [comment]
interestingly enough this doesn't seem to be an issue on the ios simulator - could be an issue just with the release build

**Comment by finger563** [comment]
though the month issue is present on both device and simulator
![Simulator Screen Shot - iPhone SE - 2019-10-09 at 08 21 47](https://user-images.githubusercontent.com/213467/66485129-deb13100-ea6d-11e9-8556-f0624a381faf.png)
