### ISSUE TITLE
ios style issues

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#435]
- [x] home tab: chart labels are wrong font
- [x] activity tab: chart labels are wrong font
- [x] activity tab: range selectors are wrong style
![Screen Shot 2019-10-14 at 10 51 31 AM](https://user-images.githubusercontent.com/213467/66765085-c4fa5a00-ee70-11e9-859e-e47812357f5f.png)
![Screen Shot 2019-10-14 at 10 51 06 AM](https://user-images.githubusercontent.com/213467/66765109-d2174900-ee70-11e9-8617-7e2f8aec34e1.png)

**Comment by finger563** [comment]
after a fresh build on master these are no longer issues
