### ISSUE TITLE
Update push detection

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#486]
- [x] update confidence threshold - keep good push detection, but try to remove false positives from things like driving / arm motions
- [x] update prediction history - increase length to cut down on false positives
- [x] don't register startup detected pushes (e.g. right after model / state initialization)
- [x] update lockout time - or at least ensure that we can detect extremely high frequency pushing
- [x] If push detection is improved (e.g. fewer false positives) then we can remove the requirement for the watch to be on the wrist
- [x] allow user a setting to control push sensitivity (0 - 100% => 0.5 - 0.9 confidence threshold)
- [ ] possibly: add check for watch on charger
