### ISSUE TITLE
move apps over to production environment

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#495]
- [ ] ensure production environment matches the structure of the development environment
  - [ ] Push notifications are configured
  - [x] DailyPushTrackerActivity
  - [x] DailySmartDriveUsage
  - [x] DailyPushTrackerErrors
  - [x] WeeklyPushTrackerActivity
  - [x] WeeklySmartDriveUsage
  - [x] SmartDriveSettings
  - [x] SmartDriveErrors
  - [x] copy  collection hooks
  - [x] copy custom endpoints
  - [x] copy common code
  - [x] copy scheduled code
  - [x] final version (2.0) firmware files + change notes are copied over
  - [x] final version (1.0) language files are copied over
- [x] update PT.M to point to production
- [x] update PT.W to point to production
- [x] update SD.W to point to production

**Comment by finger563** [comment]
the apps have been moved over to production on [feature/prod](/max-mobility/permobil-client/tree/feature/prod) - this branch will not be merged into master, but master will merged into it for production release after version bumps and such

**Comment by finger563** [comment]
@bradmartin  can we copy over the push configuration from development environment to production?

**Comment by bradmartin** [comment]
ehhhh... I always forget the configuration for push between ios/android and the specifics for environments. I don't think it's copy/paste, I think you need production certs for production.

**Comment by finger563** [comment]
sounds good - but AFAIK this is entirely server side, right - so we don't need to do anything for our release builds and we can update the backend after the release?

**Comment by bradmartin** [comment]
yes nothing should be needed to be in the app code for the switch

**Comment by finger563** [comment]
Sounds good - i'll close this issue for now and we can update the backend later this week or next week.
