### ISSUE TITLE
Add FAQs from curtis

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#503]
- [x] add faq language
- [x] update faqs to have categories
- [x] update faq to support showing links
- [x] add category filtering / display to support page
- [x] input correct links
- [x] style links properly
- [x] have links actually open to the right place

**Comment by finger563** [comment]
[PermobilPTE2_FrequentlyAskedQuestions.pdf](https://github.com/Max-Mobility/permobil-client/files/3836975/PermobilPTE2_FrequentlyAskedQuestions.pdf)
