### ISSUE TITLE
Let users know about updates

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#516]
For both PushTracker and Switch Control settings.
- [x] if they pair a pushtracker which is out of date or which reports a smartdrive which is out of date
- [x] if they try to change settings which require the latest update
- [x] if they connect to / sync settings with a smartdrive which is out of date

Like #515 we need to discuss with ben about what the messaging should be and when / where to alert the users.

**Comment by p-ranav** [comment]
Let's merge 520 and do this in a separate branch?
