### ISSUE TITLE
Data Privacy and Usage Consent

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#53]
Need the same language for data collection / privacy / usage consent as the smart eval app.
- [x] copy form over
- [x] update languge
- [x] link to user account data
- [x] link to it in profile tab
- [ ] show it during account creation
