### ISSUE TITLE
Add help page to settings page

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#733]
Using the same ? icon from the profile tab probably

* PTE2:
 - [ ] Inform them how / where to change SD settings and how the PTE2 controls the settings to the SD, so the app cannot set the settings - and how they have to re-connect to the SD using the main screen to send the settings to the SD
 - [ ] Inform them how / where to perform SD updates on the PTE2
 - [ ] Inform them how to configure and use the switch controls (use PTE2
* PT:
 - [ ] Inform them how / where to perform SD & PT updates
 - [ ] inform them how / where to set the settings, and how the PT controls the settings to the SD, so the app's settings must be sent to the PT and then from the PT to the SD
 - [ ] Inform them how to configure and use the switch controls (use app, send to PT, send to SD - they'll stay that way and be usable without app / PT if needed)
* SC:
 - [ ] Inform them how / where to perform SD updates
 - [ ] Inform them how to configure and use the switch controls
