### ISSUE TITLE
Update WearOS apps to {N} 6.X / AndroidX

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#81]
## PushTracker
- [x] `property 'v7' does not exist on type 'typeof support'.` - for MainActivity extending `android.support.v7.app.AppCompatActivity.
- [x] `Expected 4 arguments, but got 3` - for MainActivity `_callbacks.onCreate(...)`.
## SmartDrive
- [x] `property 'v7' does not exist on type 'typeof support'.` - for MainActivity extending `android.support.v7.app.AppCompatActivity.
- [x] `Expected 4 arguments, but got 3` - for MainActivity `_callbacks.onCreate(...)`.

**Comment by finger563** [comment]
Waiting on https://github.com/bradmartin/nativescript-wear-os/issues/16
