### ISSUE TITLE
Determine data collection / storage / transmission intervals for sqlite storage and network transmission

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#85]
- [x] when will we update records in the table?
- [x] how granularly will we store the data (daily? hourly? - see #84 )
- [x] how often will we send to the server?
- [x] how often (and what data) will we send to pushtracker mobile?

**Comment by finger563** [comment]
Should leverage [google fitness api](https://developers.google.com/fit/android/), related #90 #86 #84

**Comment by finger563** [comment]
Closing as the discussion on #84 has determined the answers to these questions.
