### ISSUE TITLE
Add sqlite storage / usage

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#86]
Currently the table classes / configuration is set up, but not utilized.  Will need to be finalized once #85 and #84 are determined.

### Edit:
Now that #84 and #85 have been decided, we need:
- [x] ActivityService: daily entry, with half-hour records in sqlite
- [x] validate data in db
- [x] test data loading / integrity in {N}

**Comment by finger563** [comment]
Should leverage [google fitness api](https://developers.google.com/fit/android/), related #90 #84 #85
