### ISSUE TITLE
Implement bluetooth connectivity to PT and SD and wire up to ui

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#96]
- [x] advertising app service
- [x] pairing to OGPT
- [x] showing OGPT connection status
- [x] receiving version / settings / daily info from OGPT
- [x] sending time to OGPT
- [x] sending settings to OGPT
