### ISSUE TITLE
Implement app start / landing page (after login) for first run configuration

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#97]
Since people may use the pusthracker app and have one of these three configurations:
1. smartdrive with switch control only
2. smartdrive with pushtracker
3. smartdrive with pushtracker e2

And some of the ui will be different depending on the devices they have, we should ask them up front what they're setting up for.

* SmartDrive Switch Control Only:
  * the journey and home page is not useful because there is no push / coast / journey tracking, so we will want to only show profile and smartdrive settings. SmartDrive settings will be the most important / useful UI to display to the user and should be the most prominent
  * Some settings (such as ez-on and tap sensitivity) do not make sense to show
  * pushtracker Wireless Updates is not meaningful to show, but SmartDrive Wireless Updates is meaningful
* SmartDrive with PushTracker:
  * Indication of connectivity with PushTracker
  * Activity data for day (e.g. looking at activity per hour) is not possible, PT only determines activity per day, so the day view in the Activity component should be hidden or provide some text informing them that such data is only available with the PT E2.
* SmartDrive with PushTracker E2:
  * Indication of connectivity with PushTracker Wear / SmartDrive Wear Apps
  * Settings are not meaningful since they are more easily and directly controlled on the PushTracker E2 SmartDrive MX2+ App
  * Wireless Updates are not meaningful since they are controlled by the SmartDrive MX2+ wear app.

### TODO:
- [x] design @ken-max 
- [x] landing page (run automatically if the app has not been configured or if the user presses the configure button in the settings page)

#### Switch Control:
- [x] don't advertise bluetooth
- [ ] journey and home page tabs should not be shown
- [x] [ez-on] setting should not be shown
- [x] [tap sensitivity] setting should not be shown
- [x] [mode] setting should not be shown
- [x] watch connectivity status should not be shown
- [x] pushtracker part of wireless updates should not be shown

#### PushTracker
- [x] do advertise bluetooth
- [x] Day's activity data (e.g. plot of half-hour increments) cannot have data so should not be shown or should inform the user that only the PushTracker E2 provides that data.

#### PushTracker E2
- [x] don't advertise bluetooth
- [x] hide all [SmartDrive] settings
- [x] hide watch connectivity
- [x] hide wireless updates

**Comment by finger563** [comment]
Something like this (note: the images used for this are under the files section of the teams channel):

![PT-MOBILE-CONFIGURATION](https://user-images.githubusercontent.com/213467/62878765-5c1b2800-bcef-11e9-9a76-35d18331c9e5.png)

**Comment by finger563** [comment]
Though we'll likely want the E2 to be at the top, followed by PushTracker, and Switch Control.

**Comment by p-ranav** [comment]
@bradmartin when you're free, can you take a stab at hiding the home and journey tabs if the configuration is Switch Control?

**Comment by bradmartin** [comment]
Will do. Might ping you to double check that configuration but I had another idea on that approach yesterday but didn't get to check it. 

If all else fails I'll ask the core team on slack if they have any ideas or suggestions

**Comment by p-ranav** [comment]
@bradmartin any luck with this?

**Comment by p-ranav** [comment]
I've implemented a solution to this:
1. When you change the configuration, the app says 'Login required' and redirects you to the login page
2. When you login again, the tabs component will reinitialize (*ngIf) and only show you the relevant tabs. 

When the app is in 'Switch Control with SmartDrive' configuration, you get redirected to the profile page. I think this is a reasonable solution for now.
